// <auto-generated />
using System;
using ItoApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItoApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItoApp.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.BenhNhan", b =>
                {
                    b.Property<long>("BenhNhan_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BenhNhan_Id"));

                    b.Property<int?>("BenhAn_Id_CLS")
                        .HasColumnType("int");

                    b.Property<string>("CMND")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ChiNhanh_Id")
                        .HasColumnType("int");

                    b.Property<int?>("CongTy_Id")
                        .HasColumnType("int");

                    b.Property<int?>("DanToc_Id")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Id_Old")
                        .HasColumnType("int");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Login_Id_Tao")
                        .HasColumnType("int");

                    b.Property<string>("MaYTe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NgheNghiep_Id")
                        .HasColumnType("int");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NguoiTao_Id")
                        .HasColumnType("int");

                    b.Property<string>("NhomMau")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NoiLamViec")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("QuanHuyen_Id")
                        .HasColumnType("int");

                    b.Property<int?>("QuocTich_Id")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoaiNguoiLienHe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoNha")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenBenhNhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKhongDau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TheoDoiTienSu")
                        .HasColumnType("int");

                    b.Property<string>("TienSu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TiepNhan_Id")
                        .HasColumnType("int");

                    b.Property<int?>("TinhThanh_Id")
                        .HasColumnType("int");

                    b.Property<int?>("XaPhuong_Id")
                        .HasColumnType("int");

                    b.Property<int?>("YeuToRh_Id")
                        .HasColumnType("int");

                    b.HasKey("BenhNhan_Id");

                    b.ToTable("BenhNhan", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.ChiNhanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_ChiNhanh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("MaChiNhanh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaChiNhanh");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaSoThue");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenChiNhanh");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.ToTable("ChiNhanh", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_ChucVu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenChucVu");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.ChungChiDaoTao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_ChungChiDaoTao");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChungChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("ChungChiDaoTao", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.ChungChiHanhNghe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_ChungChi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCap");

                    b.Property<DateTime?>("NgayGiaHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHetHan");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhamViChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoChungChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoChungChi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("ChungChiHanhNghe", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Dm_DichVu", b =>
                {
                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<int?>("BHYT")
                        .HasColumnType("int");

                    b.Property<int>("Cap")
                        .HasColumnType("int");

                    b.Property<int?>("CapTren_Id")
                        .HasColumnType("int");

                    b.Property<int?>("CoGia")
                        .HasColumnType("int");

                    b.Property<int?>("CongTy_Id")
                        .HasColumnType("int");

                    b.Property<int?>("DoanhThu")
                        .HasColumnType("int");

                    b.Property<int?>("DoanhThuBHYT")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("DonGia2")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("DonGiaBHYT")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("DonGiaNuocNgoai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("HeSo")
                        .HasColumnType("float");

                    b.Property<int?>("Id_Old")
                        .HasColumnType("int");

                    b.Property<int>("Idx")
                        .HasColumnType("int");

                    b.Property<string>("KhoangCachGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Login_Id_CapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("Login_Id_Tao")
                        .HasColumnType("int");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaGoiTu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MapBHYT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhomDichVuId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLanThucHien")
                        .HasColumnType("int");

                    b.Property<int?>("SoLoaiGia")
                        .HasColumnType("int");

                    b.Property<int>("TamNgung")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenKhongDau")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenNhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThucHien")
                        .HasColumnType("int");

                    b.Property<int?>("TraKetQuaMien")
                        .HasColumnType("int");

                    b.Property<int?>("TyLeVAT")
                        .HasColumnType("int");

                    b.HasKey("DichVuId");

                    b.HasIndex("NhomDichVuId");

                    b.ToTable("Dm_DichVu", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Dm_LoaiDichVu", b =>
                {
                    b.Property<int>("LoaiDichVuId")
                        .HasColumnType("int");

                    b.Property<int>("CongTy_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Old")
                        .HasColumnType("int");

                    b.Property<int>("Idx")
                        .HasColumnType("int");

                    b.Property<int?>("Login_Id_CapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("Login_Id_Tao")
                        .HasColumnType("int");

                    b.Property<string>("MaLoaiDichVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TamNgung")
                        .HasColumnType("int");

                    b.Property<string>("TenKhongDau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoaiDichVu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LoaiDichVuId");

                    b.ToTable("Dm_LoaiDichVu", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Dm_NhomDichVu", b =>
                {
                    b.Property<int>("NhomDichVuId")
                        .HasColumnType("int");

                    b.Property<int>("Cap")
                        .HasColumnType("int");

                    b.Property<int?>("CapTren_Id")
                        .HasColumnType("int");

                    b.Property<int?>("CongTy_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Old")
                        .HasColumnType("int");

                    b.Property<int>("Idx")
                        .HasColumnType("int");

                    b.Property<int>("LoaiDichVuId")
                        .HasColumnType("int");

                    b.Property<int?>("Login_Id_CapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("Login_Id_Tao")
                        .HasColumnType("int");

                    b.Property<string>("MaNhomDichVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSo_SYT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("STT")
                        .HasColumnType("int");

                    b.Property<int?>("SoLoaiGia")
                        .HasColumnType("int");

                    b.Property<int>("TamNgung")
                        .HasColumnType("int");

                    b.Property<string>("TenKhongDau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNhomDichVu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TieuDeKetQua")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TraKetQua")
                        .HasColumnType("int");

                    b.HasKey("NhomDichVuId");

                    b.HasIndex("LoaiDichVuId");

                    b.ToTable("Dm_NhomDichVu", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Dm_PhongBan", b =>
                {
                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<int>("Cap")
                        .HasColumnType("int");

                    b.Property<int?>("CapTren_Id")
                        .HasColumnType("int");

                    b.Property<int>("ChiNhanh_Id")
                        .HasColumnType("int");

                    b.Property<int>("CongTy_Id")
                        .HasColumnType("int");

                    b.Property<int?>("GroupCha")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Old")
                        .HasColumnType("int");

                    b.Property<int>("Idx")
                        .HasColumnType("int");

                    b.Property<string>("KhoaChuyenMon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NhanVien")
                        .HasColumnType("int");

                    b.Property<string>("PhanLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PhoPhong")
                        .HasColumnType("int");

                    b.Property<int?>("PhoPhong2")
                        .HasColumnType("int");

                    b.Property<int>("QuyTrinh")
                        .HasColumnType("int");

                    b.Property<int?>("STT")
                        .HasColumnType("int");

                    b.Property<int?>("STTNhom")
                        .HasColumnType("int");

                    b.Property<int>("TamNgung")
                        .HasColumnType("int");

                    b.Property<string>("TenKhongDau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThucHienCLS")
                        .HasColumnType("int");

                    b.Property<int?>("TruongPhong")
                        .HasColumnType("int");

                    b.Property<string>("ViTri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PhongBanId");

                    b.HasIndex("CapTren_Id");

                    b.ToTable("Dm_PhongBan", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.DoctorSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentPatients")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DichVuId")
                        .HasColumnType("int");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPatients")
                        .HasColumnType("int");

                    b.Property<int?>("NhomDichVuId")
                        .HasColumnType("int");

                    b.Property<int?>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.HopDongLaoDong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_HopDong");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuongDanFileScan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHetHan");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKy");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoHopDong");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HopDongLaoDong", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.HospitalBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MapUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HospitalBranches");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.KhoaPhong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_KhoaPhong");

                    b.Property<Guid>("ChiNhanhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoaPhong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKhoaPhong");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("ChiNhanhId");

                    b.ToTable("KhoaPhong", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.KyLuat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_KyLuat");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayViPham")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nodung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("KyLuat", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.KyThuatChuyenMon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_KyThuat");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayPheDuyet")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoQuyetDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKyThuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("KyThuatChuyenMon", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.LichSuChinhSua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_LichSu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuLieuCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuLieuMoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("LichSuChinhSua", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Log_OTP", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<DateTime>("HieuLucDen")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiOTP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaOTP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Log_OTP");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_NhanVien");

                    b.Property<Guid>("ChiNhanhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChucVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HoTen");

                    b.Property<Guid>("KhoaPhongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaNhanVien");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgaySinh");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NhomNgheNghiepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChiNhanhId");

                    b.HasIndex("ChucVuId");

                    b.HasIndex("KhoaPhongId");

                    b.HasIndex("NhomNgheNghiepId");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.NhomNgheNghiep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_Nhom");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("MaNhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNhom");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NhomNgheNghiep", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.STT", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("BacSiId")
                        .HasColumnType("int");

                    b.Property<string>("ChanDoanNoiGioiThieu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ChiNhanh_Id")
                        .HasColumnType("int");

                    b.Property<int?>("CongTy_Id")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DoiTuong")
                        .HasColumnType("int");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("HanThe_Den")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HanThe_Tu")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LyDoKham")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaBenhNhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDKBD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("NamSinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiTao_Id")
                        .HasColumnType("int");

                    b.Property<int?>("PhongId")
                        .HasColumnType("int");

                    b.Property<string>("SoTheBHYT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("STT", (string)null);
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.TaiKhoanBenhNhan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BenhNhan_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhan_Id");

                    b.ToTable("TaiKhoanBenhNhan");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ResetPasswordExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.HospitalBranch", "Branch")
                        .WithMany("Appointments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItoApp.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItoApp.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.ChungChiDaoTao", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("ChungChiDaoTaos")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.ChungChiHanhNghe", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("ChungChiHanhNghes")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Dm_DichVu", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.Dm_NhomDichVu", "NhomDichVu")
                        .WithMany()
                        .HasForeignKey("NhomDichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomDichVu");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Dm_NhomDichVu", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.Dm_LoaiDichVu", "LoaiDichVu")
                        .WithMany()
                        .HasForeignKey("LoaiDichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiDichVu");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Dm_PhongBan", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.Dm_PhongBan", "Parent")
                        .WithMany()
                        .HasForeignKey("CapTren_Id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.DoctorSchedule", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.HospitalBranch", "Branch")
                        .WithMany("Schedules")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItoApp.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItoApp.Domain.Entities.Dm_PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId");

                    b.Navigation("Branch");

                    b.Navigation("Doctor");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.HopDongLaoDong", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("HopDongLaoDongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.KhoaPhong", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.ChiNhanh", "ChiNhanh")
                        .WithMany("KhoaPhongs")
                        .HasForeignKey("ChiNhanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.KyLuat", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("KyLuats")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.KyThuatChuyenMon", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("KyThuatChuyenMons")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.LichSuChinhSua", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("LichSuChinhSuas")
                        .HasForeignKey("NhanVienId");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.NhanVien", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.ChiNhanh", "ChiNhanh")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChiNhanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItoApp.Domain.Entities.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItoApp.Domain.Entities.KhoaPhong", "KhoaPhong")
                        .WithMany("NhanViens")
                        .HasForeignKey("KhoaPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItoApp.Domain.Entities.NhomNgheNghiep", "NhomNgheNghiep")
                        .WithMany("NhanViens")
                        .HasForeignKey("NhomNgheNghiepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("ChucVu");

                    b.Navigation("KhoaPhong");

                    b.Navigation("NhomNgheNghiep");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Patient", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("ItoApp.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.TaiKhoanBenhNhan", b =>
                {
                    b.HasOne("ItoApp.Domain.Entities.BenhNhan", "BenhNhan")
                        .WithMany()
                        .HasForeignKey("BenhNhan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.ChiNhanh", b =>
                {
                    b.Navigation("KhoaPhongs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.HospitalBranch", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.KhoaPhong", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.NhanVien", b =>
                {
                    b.Navigation("ChungChiDaoTaos");

                    b.Navigation("ChungChiHanhNghes");

                    b.Navigation("HopDongLaoDongs");

                    b.Navigation("KyLuats");

                    b.Navigation("KyThuatChuyenMons");

                    b.Navigation("LichSuChinhSuas");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.NhomNgheNghiep", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ItoApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Patient");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}


